my_f = open('task_52.txt', 'r')
content = my_f.read()
print(f'Содержимое файла: \n{content}')
my_f = open('task_52.txt', 'r')
content = my_f.readlines()
print(f'\nКоличество строк в файле - {len(content)}')
my_f = open('task_52.txt', 'r')
content = my_f.readlines()
for i in range(len(content)):
    print(f'Количество символов {i + 1} строки - {len(content[i])}')
my_f = open('task_52.txt', 'r')
content = my_f.read()
content = content.split()
print(f'Общее количество слов - {len(content)}')
my_f.close()